name: Checkout

on: workflow_dispatch

jobs:
  initialize_repo:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      
