name: Checkout

on: workflow_dispatch

jobs:
  initialize_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: echo done
        run: echo "done"
      
